import { useState } from 'react';
import { Download, ChevronUp, ChevronDown } from 'lucide-react';
import { DpiResult, DpiFlowDetail } from '../../services/dpiApi';
import { APP_COLORS, TCP_STATE_STYLE, ACTION_STYLE, ANOMALY_STYLE, fmtBytes } from './constants';

export default function DpiResults({ result }: { result: DpiResult & { blockedFlows?: number } }) {
    const [showFlows, setShowFlows] = useState(false);
    const [showDomains, setShowDomains] = useState(false);

    const downloadReport = () => {
        const sep = '═'.repeat(55);
        const hr = '─'.repeat(55);
        const pad = (s: string, w: number) => s.padEnd(w);
        const lines: string[] = [
            sep, '      Standor DPI Analysis Report', sep,
            `Analysed  : ${new Date(result.analysedAt).toLocaleString()}`,
            `Packets   : ${result.totalPackets}`, `Flows     : ${result.activeFlows}`,
            `Class Rate: ${result.classificationRate}%`,
            `Forwarded : ${result.forwarded}`, `Dropped   : ${result.dropped}`,
            result.blockedFlows ? `Rule-blocked: ${result.blockedFlows}` : '',
            '', sep, 'Application Distribution', hr,
            `${pad('Application', 22)} ${pad('Flows', 8)} %`, hr,
        ];
        result.appStats.forEach(({ app, count, percent }) => lines.push(`${pad(app, 22)} ${pad(String(count), 8)} ${percent}%`));
        if (result.detectedDomains.length > 0) {
            lines.push('', sep, 'Top Domains', hr);
            result.detectedDomains.slice(0, 30).forEach(({ domain, app, count }) => lines.push(`${pad(domain, 40)} ${pad(app, 15)} ${count}`));
        }
        lines.push('', sep, `Generated by Standor DPI Engine — ${new Date().toISOString()}`, sep);
        const blob = new Blob([lines.filter(Boolean).join('\n')], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `standor-dpi-report.txt`; a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-5">
            {/* Stats grid */}
            <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                {[
                    { label: 'Packets', value: result.totalPackets.toLocaleString(), color: 'text-white' },
                    { label: 'Flows', value: result.activeFlows.toLocaleString(), color: 'text-indigo-400' },
                    { label: 'Classified', value: `${result.classificationRate}%`, color: 'text-emerald-400' },
                    { label: 'Forwarded', value: result.forwarded.toLocaleString(), color: 'text-green-400' },
                    { label: 'Dropped', value: result.dropped.toLocaleString(), color: 'text-red-400' },
                    { label: 'Rule-Blocked', value: (result.blockedFlows ?? 0).toString(), color: 'text-orange-400' },
                ].map(({ label, value, color }) => (
                    <div key={label} className="p-3 rounded-lg bg-white/[0.02] border border-white/[0.06] text-center">
                        <div className="text-[9px] text-neutral-600 mb-1 uppercase tracking-wider">{label}</div>
                        <div className={`text-lg font-mono font-bold ${color} leading-none`}>{value}</div>
                    </div>
                ))}
            </div>

            {/* Classification rate bar */}
            {result.classificationRate > 0 && (
                <div>
                    <div className="flex items-center justify-between mb-1.5">
                        <span className="text-[10px] font-semibold text-neutral-500 uppercase tracking-wider">Classification Rate</span>
                        <span className="text-sm font-mono font-bold text-indigo-400">{result.classificationRate}%</span>
                    </div>
                    <div className="h-2 rounded-full bg-white/[0.04] overflow-hidden">
                        <div className="h-full rounded-full bg-white transition-all duration-700" style={{ width: `${result.classificationRate}%` }} />
                    </div>
                </div>
            )}

            {/* Connection Stats */}
            {result.connectionStats && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-neutral-500 uppercase tracking-wider">Connection Statistics</h4>
                    <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                        {[
                            { label: 'TCP', value: result.connectionStats.tcpFlows, color: 'text-cyan-400' },
                            { label: 'UDP', value: result.connectionStats.udpFlows, color: 'text-blue-400' },
                            { label: 'Classified', value: result.connectionStats.classified, color: 'text-indigo-400' },
                            { label: 'Established', value: result.connectionStats.established, color: 'text-green-400' },
                            { label: 'SYN-only', value: result.connectionStats.synOnly, color: 'text-amber-400' },
                            { label: 'RST / FIN', value: `${result.connectionStats.closedRst}/${result.connectionStats.closedFin}`, color: 'text-red-400' },
                        ].map(({ label, value, color }) => (
                            <div key={label} className="p-2 rounded bg-black/20 text-center">
                                <div className="text-[8px] text-neutral-600 mb-0.5">{label}</div>
                                <div className={`text-[12px] font-mono font-bold ${color}`}>{value}</div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* App Breakdown */}
            {result.appStats.length > 0 && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-neutral-500 uppercase tracking-wider">Application Breakdown <span className="text-neutral-700 normal-case font-normal">(by flow)</span></h4>
                    <div className="space-y-1.5">
                        {result.appStats.slice(0, 15).map(({ app, count, percent }) => (
                            <div key={app} className="flex items-center gap-2">
                                <div className="h-2 rounded-full flex-1 bg-white/[0.04] overflow-hidden">
                                    <div className="h-full rounded-full transition-all duration-500" style={{ width: `${Math.max(2, percent)}%`, background: APP_COLORS[app] || '#6366f1' }} />
                                </div>
                                <span className="text-[10px] font-mono text-neutral-400 w-20 truncate">{app}</span>
                                <span className="text-[10px] font-mono text-neutral-600 w-16 text-right">{count} <span className="text-neutral-700">{percent.toFixed(0)}%</span></span>
                            </div>
                        ))}
                        {result.appStats.length > 15 && <div className="text-[9px] text-neutral-700 text-right">+{result.appStats.length - 15} more</div>}
                    </div>
                </div>
            )}

            {/* Top Talkers */}
            {result.topTalkers?.length > 0 && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-neutral-500 uppercase tracking-wider">Top Talkers</h4>
                    <div className="space-y-1">
                        {result.topTalkers.slice(0, 8).map(({ ip, flows, bytes, isPrivate, topApp }) => (
                            <div key={ip} className="flex items-center justify-between gap-2 py-1 px-2 rounded bg-black/20">
                                <div className="flex items-center gap-1.5 min-w-0">
                                    <span className={`text-[7px] font-bold px-1.5 py-0.5 rounded ${isPrivate ? 'bg-blue-500/10 text-blue-400' : 'bg-orange-500/10 text-orange-400'}`}>{isPrivate ? 'LAN' : 'WAN'}</span>
                                    <span className="text-[10px] font-mono text-neutral-400 truncate">{ip}</span>
                                </div>
                                <div className="flex items-center gap-2 flex-shrink-0 text-[9px] font-mono">
                                    <span className="text-neutral-500">{fmtBytes(bytes)}</span>
                                    <span className="text-neutral-700">{flows}fl</span>
                                    <span className="px-1.5 rounded" style={{ background: `${APP_COLORS[topApp] || '#6366f1'}15`, color: APP_COLORS[topApp] || '#6366f1' }}>{topApp}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Port Scans */}
            {result.portScans?.length > 0 && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-red-400/80 uppercase tracking-wider">⚑ Port Scans ({result.portScans.length})</h4>
                    {result.portScans.map(s => (
                        <div key={s.scannerIp} className="rounded-lg bg-red-500/5 border border-red-500/10 px-3 py-2">
                            <div className="text-[10px] font-mono text-red-300 font-bold">{s.scannerIp} <span className="text-neutral-600 font-normal">{s.isPrivate ? '(LAN)' : '(WAN)'}</span></div>
                            <div className="text-[9px] text-neutral-500 mt-0.5">{s.targetsCount} hosts · ports: {s.portsTargeted.slice(0, 10).join(', ')}</div>
                        </div>
                    ))}
                </div>
            )}

            {/* Anomalies */}
            {result.protocolAnomalies?.length > 0 && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-amber-500/80 uppercase tracking-wider">⚠ Protocol Anomalies ({result.protocolAnomalies.length})</h4>
                    <div className="space-y-1 max-h-40 overflow-y-auto">
                        {result.protocolAnomalies.map((a, i) => {
                            const st = ANOMALY_STYLE[a.type] ?? { label: a.type, color: '#f59e0b' };
                            return (
                                <div key={i} className="rounded px-2.5 py-1.5" style={{ background: `${st.color}08`, border: `1px solid ${st.color}20` }}>
                                    <div className="text-[9px] font-bold mb-0.5" style={{ color: st.color }}>{st.label}</div>
                                    <div className="text-[9px] text-neutral-500 leading-tight">{a.detail}</div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            )}

            {/* Flow Details */}
            {result.flowDetails?.length > 0 && (
                <div className="space-y-2">
                    <button onClick={() => setShowFlows(v => !v)} className="w-full flex items-center justify-between text-[10px] font-semibold text-neutral-500 uppercase tracking-wider hover:text-white transition-colors">
                        <span>Flow Details ({result.flowDetails.length})</span>
                        {showFlows ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                    </button>
                    {showFlows && (
                        <div className="space-y-1 max-h-64 overflow-y-auto">
                            {result.flowDetails.map((f: DpiFlowDetail & { blockedByRule?: string }, i: number) => {
                                const st = TCP_STATE_STYLE[f.state] || { label: f.state, color: '#6366f1' };
                                const act = ACTION_STYLE[f.action] || { label: f.action, color: '#22c55e' };
                                return (
                                    <div key={i} className="rounded-lg bg-black/20 px-3 py-2 space-y-1">
                                        <div className="flex items-center justify-between gap-1">
                                            <span className="text-[9px] font-mono text-neutral-400 truncate">{f.src}:{f.srcPort} → {f.dst}:{f.dstPort}</span>
                                            <div className="flex items-center gap-1 flex-shrink-0">
                                                <span className="text-[7px] font-bold px-1 rounded" style={{ background: `${act.color}22`, color: act.color }}>{act.label}</span>
                                                <span className="text-[7px] font-bold px-1 rounded" style={{ background: `${st.color}22`, color: st.color }}>{st.label}</span>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2 flex-wrap text-[8px] font-mono text-neutral-600">
                                            <span style={{ color: APP_COLORS[f.app] || '#6366f1' }}>{f.app}</span>
                                            <span>↑{fmtBytes(f.bytesIn)}</span><span>↓{fmtBytes(f.bytesOut)}</span>
                                            {f.durationMs > 0 && <span>{f.durationMs}ms</span>}
                                            {f.sni && <span className="text-neutral-700 truncate max-w-[200px]">{f.sni}</span>}
                                            {f.blockedByRule && (
                                                <span className="px-1 rounded text-[7px] font-bold bg-red-500/20 text-red-400">✕ {f.blockedByRule}</span>
                                            )}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>
            )}

            {/* Detected Domains */}
            {result.detectedDomains?.length > 0 && (
                <div className="space-y-2">
                    <button onClick={() => setShowDomains(v => !v)} className="w-full flex items-center justify-between text-[10px] font-semibold text-neutral-500 uppercase tracking-wider hover:text-white transition-colors">
                        <span>Detected Domains ({result.detectedDomains.length})</span>
                        {showDomains ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                    </button>
                    {showDomains && (
                        <div className="max-h-40 overflow-y-auto space-y-0.5">
                            {result.detectedDomains.map(({ domain, app, count }) => (
                                <div key={domain} className="flex items-center justify-between py-0.5 gap-2">
                                    <span className="text-[10px] font-mono text-neutral-400 truncate min-w-0">{domain}</span>
                                    <div className="flex items-center gap-1.5 flex-shrink-0">
                                        {count > 1 && <span className="text-[8px] font-mono text-neutral-600">×{count}</span>}
                                        <span className="text-[8px] font-bold px-1.5 py-0.5 rounded" style={{ background: `${APP_COLORS[app] || '#6366f1'}15`, color: APP_COLORS[app] || '#6366f1' }}>{app}</span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            )}

            {/* Processing Stats */}
            {result.processingStats && (
                <div className="space-y-2">
                    <h4 className="text-[10px] font-semibold text-neutral-500 uppercase tracking-wider">FP Processing Stats</h4>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                        {[
                            { label: 'SNI extracted', value: result.processingStats.sniExtractions },
                            { label: 'ALPN extracted', value: result.processingStats.alpnExtractions },
                            { label: 'Named apps', value: result.processingStats.classificationHits },
                            { label: 'DNS queries', value: result.processingStats.dnsExtractions },
                            { label: 'HTTP hosts', value: result.processingStats.httpHostExtractions },
                            { label: 'QUIC detected', value: result.processingStats.quicDetections },
                        ].map(({ label, value }) => (
                            <div key={label} className="flex items-center justify-between px-2.5 py-1.5 rounded bg-black/20">
                                <span className="text-[9px] text-neutral-600">{label}</span>
                                <span className="text-[10px] font-mono text-white font-bold">{value.toLocaleString()}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Footer */}
            <div className="flex items-center justify-between pt-2 border-t border-white/[0.06]">
                <span className="text-[9px] text-neutral-700">Analysed {new Date(result.analysedAt).toLocaleString()}</span>
                <button onClick={downloadReport} className="text-[10px] font-bold text-indigo-400 hover:text-indigo-300 transition-colors flex items-center gap-1">
                    <Download size={11} /> Download Report
                </button>
            </div>
        </div>
    );
}
